(GW) fff-gateway: Do not reset whole switch in configuregateway
Instead of (again) setting up the whole switch in
/etc/config/gateway, after this patch only "changes" will need to
be set up there.

For adding or updating a VLAN:

config add_vlan
	option vlan '11'
	option ports '0t 4'

For removing a VLAN (e.g. if the VLAN ID is changed):

config del_vlan
	option vlan '2'

The config blocks can be named, but the name is not evaluated.

If no change is desired (e.g. to work with default config) or if
config has already been updated otherwise (e.g. in
/etc/firstbootfff), none of the blocks is necessary.

However, one will still have to assign the VLAN IDs to the client,
batman, etc. blocks, e.g.

config batman
        option vlan '3'

In addition to the new setup rules, the CPU port now needs to be
specified by the user. This removes the old code to set it.

Signed-off-by: Adrian Schmutzler <freifunk@adrianschmutzler.de>

diff --git a/src/packages/fff/fff-gateway/files/etc/gateway.d/20-vlan b/src/packages/fff/fff-gateway/files/etc/gateway.d/20-vlan
--- a/src/packages/fff/fff-gateway/files/etc/gateway.d/20-vlan
+++ b/src/packages/fff/fff-gateway/files/etc/gateway.d/20-vlan
@@ -1,38 +1,47 @@
 # Load libraries
 . /lib/functions.sh
-. /lib/functions/fff/cpuport
 
 add_vlan() {
-	local vlan="$1"
-	local name="vlan$vlan"
-	local device="$(uci get network.@switch[0].name)"
-	local ports="$(uci get gateway.$vlan.ports)"
+	local name="$1"
+	local vlan="$(uci -q get gateway.$name.vlan)"
 
-	uci set network.$name='switch_vlan'
-	uci set network.$name.device="$device"
-	uci set network.$name.vlan="$vlan"
-	uci set network.$name.ports="$CPUPORT $ports"
+	if [ -z "$vlan" ]; then
+		echo "-> Missing VLAN ID for add_vlan $name"
+		return 1
+	fi
+
+	# add switch_vlan
+	echo "-> Setting up VLAN $vlan"
+	uci set network.vlan$vlan='switch_vlan'
+	uci set network.vlan$vlan.vlan="$vlan"
+	uci set network.vlan$vlan.device="$(uci get network.@switch[0].name)"
+	uci set network.vlan$vlan.ports="$(uci get gateway.$name.ports)"
 }
 
 remove_vlan() {
 	local name="$1"
-	local vlan=$(echo $name | sed 's/vlan//')
+	local vlan="$(uci -q get gateway.$name.vlan)"
 
-	# only remove vlans not present in gateway config
-	if ! uci -q get gateway.$vlan > /dev/null; then
-		# remove switch_vlan
-		uci del network.$name
+	if [ -z "$vlan" ]; then
+		echo "-> Missing VLAN ID for del_vlan $name"
+		return 1
+	fi
+
+	# remove switch_vlan
+	echo "-> Deleting VLAN $vlan"
+	if ! uci -q del network.vlan$vlan ; then
+		echo "-> Error deleting VLAN $vlan"
 	fi
 }
 
 configure() {
-	echo "Removing unused VLAN entries"
-	config_load network
-	config_foreach remove_vlan switch_vlan
-
-	echo "Setting up VLAN entries"
+	echo "Removing VLAN entries"
 	config_load gateway
-	config_foreach add_vlan vlan
+	config_foreach remove_vlan del_vlan
+
+	echo "Adding VLAN entries"
+	config_load gateway
+	config_foreach add_vlan add_vlan
 }
 
 apply() {
