(GW) fff-gateway: Check length of peering interface name
Signed-off-by: Adrian Schmutzler <freifunk@adrianschmutzler.de>

diff --git a/src/packages/fff/fff-gateway/files/etc/gateway.d/60-babelpeer b/src/packages/fff/fff-gateway/files/etc/gateway.d/60-babelpeer
--- a/src/packages/fff/fff-gateway/files/etc/gateway.d/60-babelpeer
+++ b/src/packages/fff/fff-gateway/files/etc/gateway.d/60-babelpeer
@@ -72,6 +72,12 @@ add_peer() {
 		exit 1
 	fi
 
+	# ensure name length
+	if [ ${#name} -gt 15 ]; then
+		echo "ERROR: name $name is too long!"
+		exit 1
+	fi
+
 	# add interface
 	uci set network.$name=interface
 
