bsp: Use custom scheme to define devices and packages
This is inspired by the target config files in Gluon, although
this approach works quite differently in detail.

For each target, a .bsp file in bsp/ is created, where devices
and packages are specified with predefined commands. This makes
definitions more compact and less redundant.

The .config file is then constructed during every run of
buildscript and put into bsp/config/<target>.config

Existing files there will be overwritten.

If "buildscript config openwrt" is used, the result will be put
into bsp/config/<target>.openwrt for examination.

Signed-off-by: Adrian Schmutzler <freifunk@adrianschmutzler.de>

diff --git a/buildscript b/buildscript
--- a/buildscript
+++ b/buildscript
@@ -221,7 +221,7 @@ prebuild() {
     mkdir "$target"/files
 
     cp -r ./bsp/default/root_file_system/* "$target"/files/
-    cp ./bsp/"$machine"/.config "$target"/.config
+    cp "$configfile" "$target"/.config
 
     while IFS= read -r -d '' template
     do
@@ -303,10 +303,10 @@ config() {
     if [ "$save" = "y" ]; then
         case "$1" in
             "openwrt")
-                echo "# Generated using \"./buildscript config openwrt\"." > "$opath"/bsp/"$machine"/.config
-                echo "# Do no edit manually" >> "$opath"/bsp/"$machine"/.config
-                echo "#" >> "$opath"/bsp/"$machine"/.config
-                ./scripts/diffconfig.sh >> "$opath"/bsp/"$machine"/.config
+                echo "# Generated using \"./buildscript config openwrt\"." > "$opath"/bsp/config/"$machine".openwrt
+                echo "# Do no edit manually" >> "$opath"/bsp/config/"$machine".openwrt
+                echo "#" >> "$opath"/bsp/config/"$machine".openwrt
+                ./scripts/diffconfig.sh >> "$opath"/bsp/config/"$machine".openwrt
                 ;;
         esac
     fi
@@ -317,7 +317,9 @@ config() {
 cp_firmware() {
     [ -n "$subtarget" ] || subtarget="generic"
 
-    for image in ${images[@]}; do
+    #for image in ${images[@]}; do
+    for dev in $devices; do
+        image="openwrt-${imagetarget/_/-}-${dev}-squashfs-sysupgrade.bin"
         filename_build=${image//openwrt/fff-${version}}
         filename_build=${filename_build//generic/g}
         filename_build=${filename_build//tiny/t}
@@ -395,7 +397,21 @@ clean() {
 
 loadBSP()
 {
-    echo "Working with $(/bin/ls -l selected_bsp | awk '{ print $11 }')"
+    bspfile="$(/bin/ls -l selected_bsp | awk '{ print $11 }')"
+    echo "Working with $bspfile"
+    machine=$(echo "$bspfile" | sed -e 's#^bsp/##' -e 's#\.bsp$##')
+
+    if [ -z "$machine" ]; then
+        echo "Error: BSP file naming scheme incorrect!"
+        exit 1
+    fi
+
+    target=$builddir/$machine
+    configfile="./bsp/config/${machine}.config"
+    [ ! -d ./bsp/config ] && mkdir ./bsp/config
+    > "$configfile"
+
+    . ./bsp/buildlib
     . selected_bsp
 }
 
